### PR TITLE
Add columnGap to viz inputs and marginRight to y-axis agg input title

### PR DESCRIPTION
**Pull request by jernestmyers**
Addresses [first part of this issue](https://github.com/VEuPathDB/web-eda/issues/1381).

### CODE REVIEW

**Comment by chowington** [comment]
@jernestmyers Looks like this issue is resolved on main now?

image

**Comment by chowington** [comment]
I'll approve though just in case there's an improvement I'm missing

**Review by chowington — APPROVED** [review]

**Comment by jernestmyers** [comment]
The issue never did surface while developing on a local dev site. There must be some sylesheet that interfered with my original styling, so now you've reminded me that I should try to build this on a dev site and see if the styling is what I'm expecting!

**Review by bobular — APPROVED** [review]
Looks good!

**Pull request merged**
