### PR TITLE
conditional yLabel as Proportion, switching string to date variable bug

### PR DESCRIPTION
**Pull request by moontrip**
This addresses two issues: a) [Update Y-axis labels for line plots #1050](https://github.com/VEuPathDB/web-eda/issues/1050) and [Viz: Error message in line plots when switching x-axis variable #1061](https://github.com/VEuPathDB/web-eda/issues/1061).

- For a): the Y-axis label is conditionally set to be Proportion in the line plot viz when Proportion mode is used. A example screenshot is shown in the following (SCORE S. mansoni Cluster Randomized Trial)

- For b): this is similar situation to [switching from number to date variable on scatterplot and lineplot y-axis causes an exception #1003](https://github.com/VEuPathDB/web-eda/issues/1003). For the line plot viz, categorical and/or ordinal have string type and its value is string. For a date variable, its type is date but its value is also string: more exactly, date string. So when switching string type to date type, old values of sting from string type is used as a date string, which causes the error when computing axis range margin. To resolve this, a condition is set to check whether it is date type as well as date string value using Date.parse(). 

- screenshot of Y-axis label as Proportion
lineplot-yaxis-label

### CODE REVIEW

**Comment by bobular** [comment]
I haven't reviewed yet, but I am wondering if the continuous y-axis variables should have y axis labels: "Mean Age", "Median Age" ? @danicahelb

**Comment by bobular** [comment]
Hi @moontrip - I don't see this bit implemented

```
For mean and median modes, add "Mean: " or "Median: "
For example, the label should look like "Mean: Age (years)"
```

**Comment by moontrip** [comment]
@bobular Thank you for your suggestion. I will add them 👍

**Review by bobular — APPROVED** [review]
This is great - I tested and reproduced the error and then your branch fixes it.

Unfortunately I found another bug while testing (unrelated to this) that I now have to write up...

**Comment by moontrip** [comment]
@bobular Yep as I replied at slack, I added the additional prefix for Mean and Median options. Here are screenshots. Are they alright for you?

lineplot-mean

lineplot-median

**Comment by moontrip** [comment]
Bob liked and approved my changes at slack so I will merge this PR

**Pull request merged**
