### PR TITLE
addressing a couple of lineplot viz stuffs

### PR DESCRIPTION
**Pull request by moontrip**
This will address https://github.com/VEuPathDB/web-eda/issues/1079, which the required tasks are summarized at https://github.com/VEuPathDB/web-eda/issues/1079#issuecomment-1152401516.

Here are example screenshots with PRISM data

- ### before applying this PR: the first screenshot is without removing the error message (taken from the ticket) and the second one is by simply removing the error message in the code, which causes 500 error instead 

a) 
163398028-b31185d1-6051-4f28-b662-adcd082686fc

b)
lineplot-error-msg1

- ### after applying this PR: now proportion can be used without error message & numerator = denominator & showing 1
lineplot-temporary error1

- ### after applying this PR: other variable for test the case of numerator = denominator & showing 1
lineplot-numerator-denominator1

### CODE REVIEW

**Comment by moontrip** [comment]
@bobular Since you are the most familiar with the Lineplot Viz, I chose you as a reviewer 😄 Can you please check if this PR satisfies the requirement summarized by Danica, https://github.com/VEuPathDB/web-eda/issues/1079#issuecomment-1152401516? Above screenshots may be helpful too, I suppose 🤔

**Comment by danicahelb** [comment]
hi @moontrip this is what we want, thanks.

can you confirm that -- if you have subsetted the data in a way that the numerator and denominator ends up being the same -- that the plot is not throwing an error and we still get a line at y=1?

For example, in GEMS1 case control, apply a filter for Country = Bangladesh
In the line plot, you can plot x=sleeping rooms in dwelling count & y=country. then configure the proportion so that the numerator is Bangladesh & India and denominator is all countries:

image

**Comment by moontrip** [comment]
@danicahelb I have tested the case and unfortunately, it failed: if I manually adjust the numerator and denominator as Bangladesh, then it worked. 

I have briefly looked at the code and it looks to me that the list of numerator and denominator does not respect the filter. So, I think that if we limit the list by considering filters, then it would work, I suppose. I will try and see if I can do that myself, as the proportion was made by Bob

**Comment by danicahelb** [comment]
hey @moontrip the other issue I identified has its own ticket: https://github.com/orgs/VEuPathDB/projects/11/views/1

maybe check in with @asizemore about implementing?

**Comment by moontrip** [comment]
@asizemore Thank you for your explanation and sounds great to me 👍 I didn't know the presence of the backend work you were doing, so I thought it might have been a frontend stuff. I will see if I can make it from my side as well, though it's a bit tricky. 

When your work is merged, please let me know so that I can test it (with GEMS1 Danica tested) too!

**Comment by bobular** [comment]
> I have briefly looked at the code and it looks to me that the list of numerator and denominator does not respect the filter. So, I think that if we limit the list by considering filters, then it would work, I suppose. I will try and see if I can do that myself, as the proportion was made by Bob

Hi @moontrip 
I don't think it will be easy to customize the numerator and denominator choices based on the current filters. Well, it might be possible with a whole new back end request, but I don't think we want to add new complexity like that at the current late stage in release 58!

**Pull request merged**
