### PR TITLE
truncated axis for histogram filter

### PR DESCRIPTION
**Pull request by moontrip**
This PR relies on the [PR at web-components](https://github.com/VEuPathDB/web-components/pull/195). Detailed description is discussed in there.

Clean-up is not done yet.

### CODE REVIEW

**Review by bobular — COMMENTED** [review]
This is very nice, thanks.  I would like to have a look on Monday at the logic behind the dependent axis truncation flag. (I know you've been concerned about this for a week or so!)  I wonder if it's worth doing a max(bin.counts) to at least detect overflow at the top of the plot.  IIRC Danica and co are not too bothered about the underflow warning.  Or we could change the wording in the warning to "may be truncated" and leave things as they are.

**Comment by bobular** [comment]
Hi @moontrip  - I have pushed a commit that I think leaves this new feature in a functionally/scientifically acceptable state for feedback from the outreach team.

What's new is that the dependent axis lower truncation is only shown if the user-entered lower bound is > 0.  Histograms always show counts, so we never expect the dependent axis to have negative values.  (For this reason, I think `truncationConfig()` isn't going to be multi-purpose and could be moved out of the utils directory.)

The dependent axis warning has softer language than the independent axis too.

We could check the dependent axis more carefully for truncated data in the HistoViz component, but I think we should only do that if advised by ClinEpi folk, as it will be a bit messy making another pass on the data.

**Comment by bobular** [comment]
I wonder, how easy would it be to make sure that the grey bars were a similar thickness on both axes? Might be fiddly?  A Phase 2 thing, I guess.

**Comment by moontrip** [comment]
> Hi @moontrip - I have pushed a commit that I think leaves this new feature in a functionally/scientifically acceptable state for feedback from the outreach team.
> 
> What's new is that the dependent axis lower truncation is only shown if the user-entered lower bound is > 0. Histograms always show counts, so we never expect the dependent axis to have negative values. (For this reason, I think `truncationConfig()` isn't going to be multi-purpose and could be moved out of the utils directory.)
> 
> The dependent axis warning has softer language than the independent axis too.
> 
> We could check the dependent axis more carefully for truncated data in the HistoViz component, but I think we should only do that if advised by ClinEpi folk, as it will be a bit messy making another pass on the data.

@bobular Thank you for your changes 👍 As for the truncationConfig(), it may also be utilized for other plot vizs like passing additional argument, e.g, plot name like 'histogram', I suppose.

**Comment by moontrip** [comment]
> I wonder, how easy would it be to make sure that the grey bars were a similar thickness on both axes? Might be fiddly? A Phase 2 thing, I guess.

@bobular Well I think it has inherent difficulties due to: a) plot width and height are quite different (not square but wide rectangle); b) the range of X is quite different from Y; c) there is log scale as well; d) the width of plot is basically automatic, i.e., depending on browser's size, while plot height (Y) is fixed. Also, different browser's zoom level also affects plot width. Thus, it would be a daunting task to find equal bar widths, I suppose.

**Review by jtlong3rd — APPROVED** [review]

**Pull request merged**
