### PR TITLE
adding units

### PR DESCRIPTION
**Pull request by moontrip**
This PR addresses #340, General: add units where needed on subset & visualize tabs.

A couple of screenshots are attached:

weight1

scatter-unit1

histogram-unit1

### CODE REVIEW

**Comment by moontrip** [comment]
@jtlong3rd Thank you for your review 👍 It is quite fast, so I wonder you keep waiting for a PR to review 😄

**Review by bobular — CHANGES_REQUESTED** [review]
I'll message Danielle in the Slack channel to double check my comments about unnecessary units code are valid

**Comment by bobular** [comment]
Discussion here
https://epvb.slack.com/archives/C012ZK4Q5CZ/p1630533616005900

Maybe we should keep it.  There could be a variable with limited values: 1 kg, 2 kg, 3 kg, 4 kg.

**Comment by moontrip** [comment]
> Discussion here
> https://epvb.slack.com/archives/C012ZK4Q5CZ/p1630533616005900
> 
> Maybe we should keep it. There could be a variable with limited values: 1 kg, 2 kg, 3 kg, 4 kg.

@bobular thank you for your review! 👍 Since I can't check all possible whether a variable would have unit or not, I just wrapped up all variables' name with a function to add units if exists: if not, then same to variable name. This is a safe/conservative approach 😄

**Review by dmfalke — APPROVED** [review]

**Pull request merged**
