### PR TITLE
multifilter assign colors to distribution bars

### PR DESCRIPTION
**Pull request by asizemore**
With WDKClient [PR #153](https://github.com/VEuPathDB/WDKClient/pull/153) , specifies colors for the stacked bars in multifilter subsetting tab table. 

Previous PR #377  updated the above for numeric and categorical variables, but not for multifilter. See also issue #301 for more details.

### CODE REVIEW

**Review by bobular — APPROVED** [review]
Code review only (no testing): this and the WDK changes look good!

**Review by dmfalke — APPROVED** [review]
Looks great! Just leaving a reminder to upgrade the version of `@veupathdb/wdk-client` used here once https://github.com/VEuPathDB/WDKClient/pull/153 is merged and a new version is published.

**Comment by dmfalke** [comment]
New version is `0.4.4`

**Comment by asizemore** [comment]
Great. wdk-client version updated. Thank you both!

**Pull request merged**
