### PR TITLE
Clean up console logs

### PR DESCRIPTION
**Pull request by jernestmyers**
Related to Issue #585 

I initially tried to remove this handler from `MultiSelectVariableTree`:
```js 
const onActiveFieldChange = useCallback((term?: string) => {
  console.log('Hello from Multi-Select onActiveFieldChange', term);
}, []);
```
That led me to discover that `VariableList` receives the `onActiveFieldChange` handler from two sources, thus simply removing it and its references proved problematic. But without the `console.log` it's essentially doing nothing now which feels very odd:
```js
  const onActiveFieldChange = useCallback((term?: string) => {}, []);
```

### CODE REVIEW

**Comment by bobular** [comment]
Hi Jeremy,
Unbeknownst (what a word!) to you, Dave worked on the MultiSelectVariableTree source in a recently merged PR: https://github.com/VEuPathDB/web-eda/pull/894 
So you may want to try to revert your changes in that file (I would have to google that!), then merge in main (`git merge origin/main` or `git merge main` if you have already checked out the latest version locally).

**Comment by jernestmyers** [comment]
Doh! Okay, I'll look into the necessary git commands to revert the changes.

**Comment by bobular** [comment]
> Doh! Okay, I'll look into the necessary git commands to revert the changes.

Yeah just your luck that he worked on the same handler!

**Comment by dmfalke** [comment]
Apologies for creating a conflict! Rather than reverting that commit, I would suggesting doing `git merge main` and handling the merge conflict. It's good practice!

**Comment by jernestmyers** [comment]
Okay, I think I addressed the merge conflict.

**Comment by bobular** [comment]
Looks good!

**Review by dmfalke — APPROVED** [review]
Looks good!

**Pull request merged**
