### PR TITLE
add variable.definition

### PR DESCRIPTION
**Pull request by moontrip**
add variable.definition below variable selector at viz. Here is a screenshot

display-definition

### CODE REVIEW

**Comment by moontrip** [comment]
moved style to scss

**Review by bobular — COMMENTED** [review]
Hi DK.

I'm seeing layout of z-axis issues when a server response error is shown

image

What's the longest variable definition we are likely to get?  And is there a plan for these long ones?

Finally, is this task only concerning the `InputVariables` component?  As #197 is a little vague, I suggest these also as important
1. mouse-over in the VariableTree
2. display variable definition in subsetting along with the exisiting "Original variable name" (I would expect to see the full definition on mouse-over the (?) icon - rather than the rather boring generic mouseover currently there) - or maybe add a (i) icon ('i' for information)

**Comment by moontrip** [comment]
@bobular yes I am aware of that overlapping issue with (error) messages but does not have clear answer to address. It is because the current text of variable.definition is associated with each variable selector to be shown appropriately in space (esp. width). It may be okay for demo purpose ? 🤔 
One possible solution is to use mouse-over to a simple text, like showing 'variable definition' text at the bottom of variable selector and add mouse-over event on the text.

Yes the ticket is ambiguous. I understood that the ticket was for Viz's variable selector, so perhaps it needs more clear description on its scope and work to be done.

**Comment by dmfalke** [comment]
@DK I don't think this was the intended place for the variable definition. This should be in the subsetting tab, below the "Original variable name":
image

**Comment by moontrip** [comment]
@dmfalke aha I see. One quick question: do we need a prefix for variable.definition (like `Variable definition: {variable.definition}` or simply show the contents of variable.definition (`{variable.definition}`) in there?

**Comment by dmfalke** [comment]
This is what we're doing on the live site
image

We don't have a prefix, which I think it fine. On the live site, the definition comes before the provider label. It makes more sense to me for it to come after, so I would do that.

**Comment by moontrip** [comment]
@dmfalke is this acceptable ? I set small margins at top and bottom

variabledefinition1

variabledefinition2

**Comment by dk** [comment]
Hi all, please don't cc me. Thanks

**Review by dmfalke — APPROVED** [review]

**Review by jtlong3rd — APPROVED** [review]

**Comment by moontrip** [comment]
merging this PR. Perhaps Bob's comment above may be discussed in the mtg or issue

**Pull request merged**
