### PR TITLE
Render asterisks for required inputs' labels

### PR DESCRIPTION
**Pull request by jernestmyers**
Partially addresses #1177.

Currently only renders the asterisks next to inputs that are classified as `isRequired` in the `constraints` prop. This does not include the function or proportion inputs. The asterisks will be added to the function and proportion inputs as part of the work outlined in issue #1038.

### CODE REVIEW

**Review by bobular — COMMENTED** [review]
So sorry for the long turnaround time, Jeremy.

I love the logic/implementation, but from the user's point of view they will need to know what the asterisk means. Either with a legend/footnote somewhere, or a mouse-over.

We should also consider removing the "(optional)" from the Stratification variables section.

Is this still going through some UX decision process? @danicahelb

**Comment by jernestmyers** [comment]
Great points. I agree that we have no need for "(optional)" now that we're indicating what is required, thereby implying all other inputs are optional. I'll wait to hear what Danica thinks both about excising "optional" and about providing the user information about the asterisk.

Thanks for the feedback.

**Comment by jernestmyers** [comment]
I just pushed the following changes:
- Removed "(optional)" from `Stratification variables (optional)` label
- Replaced the `Y-axis aggregation`'s tooltip with the `HelpIcon` from `web-components`; this serves two purposes: fixes the slow render of the tooltip (was using the default 1 second hover before rendering) and moves toward unifying help icons to look/feel the same throughout the site
- Also replaced the `BirdsEyeView`'s tooltip with the `HelpIcon`
- Added a tooltip to the axis labels that reads `Required input`

**Comment by danicahelb** [comment]
@jernestmyers please see comments in https://github.com/VEuPathDB/EdaNewIssues/issues/407

**Comment by jernestmyers** [comment]
Addresses #1322

**Review by dmfalke — APPROVED** [review]
This all looks good to me!

**Pull request merged**
