### PR TITLE
Use Material UI tooltips

### PR DESCRIPTION
**Pull request by dmfalke**
This PR utilizes tooltips from the Material UI library. We may want to use these tooltips in other parts of the EDA workspace, such as places where we are currently relying on system tooltips (via the `title` attributes).

### CODE REVIEW

**Comment by dmfalke** [comment]
I'm looking for feedback on whether we should use the `Tooltip` component in more places, or stick with the current set of changes.

**Review by jtlong3rd — APPROVED** [review]
I like the new tooltips! I particularly appreciate how easy it is to make them "interactive."

I'm fine with `Tooltip` / `HtmlTooltip` being adopted in more places than just your current set of changes.

**Comment by dmfalke** [comment]
I think the proper thing to do would be to add `HtmlTooltip` to https://github.com/veupathdb/web-components.

**Comment by jtlong3rd** [comment]
> I think the proper thing to do would be to add `HtmlTooltip` to https://github.com/veupathdb/web-components.

Makes sense!

**Comment by dmfalke** [comment]
One issue with using mui tooltips is that we are using some components from `wdk-client` that use a different tooltip component. This might be a good opportunity to move those components to `web-components` (but there may be obstacles with that...).

**Comment by dmfalke** [comment]
Or, we can update wdk-client to use mui tooltips.

**Review by jtlong3rd — APPROVED** [review]

**Pull request merged**
