### PR TITLE
Implement 2-column subsetting modal layout

### PR DESCRIPTION
**Pull request by chowington**
Fixes https://github.com/VEuPathDB/web-eda/issues/935
Depends on https://github.com/VEuPathDB/CoreUI/pull/70

### CODE REVIEW

**Comment by jernestmyers** [comment]
The download modal looks **_really_** good! I'm only playing with the UI currently and haven't yet dug into the code, but I do wonder about some stylistic things that stood out:

1. Should we add some more space around the "X" that removes rows, and possibly reduce its size?
2. Do we want any sort of hover effect on the "X"?
3. Should the lock icon be centered vertically in line with the column header text? It appears to be centered vertically [in the Figma mockup](https://www.figma.com/file/P4jtVBKMdq18fc4C9HqVGp/Subsetting-results-download-modal?node-id=351%3A20227).

image

**Comment by chowington** [comment]
Thanks @jernestmyers for the comments! I'll respond here:

1. I can look into this for sure
2. Yeah, hover effects are helpful! I sometimes skimp on them when doing styling with React's `style` prop because it doesn't support them, but that's not a good excuse 😅 
3. I choose to put the lock icon in the corner like the X button is mainly because having it vertically centered looked odd when the headings had multiple lines of text (which in practice happens a lot), but also I thought it gave a nice visual link between the two icons.

**Comment by chowington** [comment]
Here's the updated styling:

image

On hover:

image

**Comment by chowington** [comment]
If you want to see the lock icons centered with multiple lines of text, I can reimplement that and take a screenshot of it too

**Comment by jernestmyers** [comment]
> If you want to see the lock icons centered with multiple lines of text, I can reimplement that and take a screenshot of it too

I agree with your point about how it would look strange when the column headers occupy multiple lines.

I wonder if we would prefer that the `VariableList` or `MultiSelectVariableTree` containers be scrollable when the variables are expanded, as opposed to the modal itself becoming scrollable? When there are a lot of required columns, real estate is limited so scrolling within the variable container would be awkward until the user collapses the required and featured variable sections. This is likely not urgent for the demo purposes but probably worth clarifying the desired behavior.
image

**Comment by chowington** [comment]
Done! Thanks Jeremy!

**Pull request merged**
