### PR TITLE
v1.3.5

### PR DESCRIPTION
**Pull request by jtlong3rd**

### CODE REVIEW

**Review by dmfalke — APPROVED** [review]
Did we forget to increment the version somewhere? Considering preventing merges unless a new version is declared. Has downsides though.

**Comment by jtlong3rd** [comment]
> Did we forget to increment the version somewhere?

Yes, for https://github.com/VEuPathDB/web-eda/pull/835/files. It happens!

**Comment by dmfalke** [comment]
> > Did we forget to increment the version somewhere?
> 
> 
> 
> Yes, for https://github.com/VEuPathDB/web-eda/pull/835/files. It happens!

Of course!

**Comment by eikonomega** [comment]
Oh 😭 how could I forget to add this! I even *asked* @jtlong3rd what version we should go with.
I'm LAME. 

cc @dmfalke

**Comment by dmfalke** [comment]
I've done it _many_ times.

**Pull request merged**
