### PR TITLE
Add 'My analyses' button and take search term from query param

### PR DESCRIPTION
**Pull request by chowington**
Fixes https://github.com/VEuPathDB/web-eda/issues/322

Test speed of typing in search box now---seems kinda slow in my VM, but may be faster on a real machine.

### CODE REVIEW

**Review by dmfalke — COMMENTED** [review]
This looks really great. I think we need to address the lag, before merging. The general approach I think we should take is to debounce computation of `filteredAnalysesAndDatasets`. There are a number of ways to approach this, none of which are straightforward. I will try to outline a plan later, but feel free to explore options. There may be an off-the-shelf solution out there.

**Comment by dmfalke** [comment]
This is what I came up with. It utilizes [`debounce`](lodash.com/docs#debounce) from lodash. Hopefully this is helpful.

```diff
diff --git a/src/lib/workspace/AllAnalyses.tsx b/src/lib/workspace/AllAnalyses.tsx
index f115b3d..d2e929f 100644
--- a/src/lib/workspace/AllAnalyses.tsx
+++ b/src/lib/workspace/AllAnalyses.tsx
@@ -1,4 +1,4 @@
-import { orderBy } from 'lodash';
+import { debounce, orderBy } from 'lodash';
 import Path from 'path';
 import React, { useCallback, useMemo, useState } from 'react';
 import { useRouteMatch } from 'react-router';
@@ -374,6 +374,25 @@ export function AllAnalyses(props: Props) {
     ]
   );
   const theme = createMuiTheme(workspaceTheme);
+  
+  // Create a debounced function, which will update the query param
+  // at most once every 250ms. This prevents issues with UI lag
+  // caused by rerendering the table on every character input.
+  //
+  // NB: We want to minimize the number of dependencies so that this
+  // function is as stable as possible.
+  //
+  // NB2: TextField below is no longer a controlled input component.
+  // This makes it possible to have the input state and queryparam
+  // state be out of sync, which is necessary for debouncing.
+  const updateQueryParam = useMemo(
+    () =>
+      debounce((value: string) => {
+        const queryParams = value ? `?s=${value}` : '';
+        history.replace(`${location.pathname}${queryParams}`);
+      }, 250),
+    [history, location.pathname]
+  );
   return (
     <ThemeProvider theme={theme}>
       <div className={classes.root}>
@@ -393,14 +412,9 @@ export function AllAnalyses(props: Props) {
                 size="small"
                 label="Search analyses"
                 inputProps={{ size: 50 }}
-                value={searchText}
+                defaultValue={searchText}
                 onChange={(e) => {
-                  e.target.value.length > 0
-                    ? queryParams.set('s', e.target.value)
-                    : queryParams.delete('s');
-                  history.replace(
-                    `${location.pathname}?${queryParams.toString()}`
-                  );
+                  updateQueryParam(e.target.value);
                 }}
               />
               <span>
```

**Comment by chowington** [comment]
Thanks for this @dmfalke! Ready for review again.

**Review by dmfalke — APPROVED** [review]
This looks great! I'm adding @jtlong3rd as a reviewer, just in case he spots any concurrency issues with how `debounce` is being used here.

**Review by jtlong3rd — APPROVED** [review]

**Pull request merged**
