### PR TITLE
Subset datagrid ux tasks  2022 02

### LINKED ISSUE #656: Bugs in subsetting results data table modal & subset download files
- [x] Uncomment button to invoke modal
- [x] Update styling of close button for modal (use an X in the top-right corner)
- [x] Update styling of variable selector toggle (possibilities: change label on state change; add a close icon; or make look even more like a drop-down menu)

QA Tasks (each tagged w/ assignee)
- [x] Incorrect URL is hardcoded for the tabular download (@dmfalke)
- [x] Reflect starred variables in the variable selector drop-down. (@dmfalke)
- [x] Allow user to add/remove starred variables from the selector drop-down. (@dmfalke)
- [x] Have the tree expanded by default in the selector drop-down. (@dmfalke)
- [x] Look into the data loading errors mentioned by Danica. (@dmfalke)
- [x] It would be good to have the featured variables box above the variable selector. (@dmfalke)
- [x] See if we can remove the "select all | clear all | expand all | collapse all" footer to give more real estate to the variable tree. (@dmfalke)
- [ ] When a user is not logged on / does not have an access request approved, they cannot open the subsetting results table. Instead they see the popup instructing them to log in or request access. We had previously talked about enabling users to see 20 rows of data when they don't have access. We should discuss what functionality we'd like during an upcoming ux meeting (@dmfalke)
- [x] Re-position the variable selector window so that it is more obviously a pop-over. (@eikonomega)

### PR DESCRIPTION
**Pull request by dmfalke**
closes #656

- When a variable has units, the units should be displayed in the column header for that variable (ex: "Hemoglobin (g/dL)" in LLINEUP)
- Always show all relevant ID columns (Participant ID, Household ID, etc) even when no variables have been added to the table
- When just ID columns are in the table (ie, when no variables have been added), please display the text: To configure this table, click on the "Add columns" button. above the table (Note that the "Select variables" button is being changed to "Add columns" in this https://github.com/VEuPathDB/web-eda/issues/839)
- Never pre-populate the table with any variables (including featured and starred variables). Default view of the subsetting results table should just show columns for the relevant IDs
- In https://github.com/VEuPathDB/web-eda/issues/839, we indicate that the "Select variables" button will be moved to the left of the entity name. The variable selector tree should open below this button. Please position the variable selector tree so that we can see the table behind it (We should see the table on top of the variable selector box and also to the left and right of it)
- If I am in a new analysis and I star one of the featured variables from the browse/subset variable tree, I get an error message when I click "View and download"
- All featured variables appear in the featured variables box in the variable selector for every entity, even when they do not belong to a given entity. There is a check box next to each of the featured variables, making it seem as though I can add these variables to my results table. Please grey out and remove the check box from featured variables that do not belong to the entity the user has selected.

### CODE REVIEW

**Comment by dmfalke** [comment]
I just discovered that we're making two requests when the modal is open, and the user has selected variables. I will try to address this before merging.

**Comment by dmfalke** [comment]
I think this latest commit will do it.

**Comment by dmfalke** [comment]
@eikonomega just want to alert you to this PR, since it likely overlaps with your related work on the **Downloads** tab. Feel free to review, but I will likely go for a merge sooner rather than later :slightly_smiling_face:.

**Review by jtlong3rd — APPROVED** [review]

**Comment by dmfalke** [comment]
@eikonomega I'm planning to merge this shortly. I'm happy to work out any merge conflicts that you might run into on https://github.com/VEuPathDB/web-eda/tree/shifu__758__downloads_tab

**Pull request merged**
