### PR TITLE
Add performance warning for specific datasets - Issue #810

### PR DESCRIPTION
**Pull request by jernestmyers**
Relates to Issue #810

- Displays a performance warning when user is in the Visualize tab for these studies: Amazonia Peru, MAL-ED, and UMSP
- Performance warning persists as long as user is in the Visualize tab of one of the above studies

Question: Is the desired behavior for the performance warning to persist (as shown in the screenshot) or should user be able to "dismiss" the warning?

image

### CODE REVIEW

**Review by dmfalke — APPROVED** [review]
This looks great!

Reminder, before merging, update the package version locally using
```
yarn version --patch
git push --follow-tags
```

**Comment by jernestmyers** [comment]
Latest version makes these changes:

- Adds the ability for users to dismiss the performance warning
- Persists whether or not user has dismissed the warning to localStorage via [this new hook](https://github.com/VEuPathDB/WDKClient/pull/186/commits/db2b8d20657b658db020b225e10c5e4c9c729c4c), modeled after `useSessionBackedState`
- Ensures that a user sees the performance warning at least one time for each study by using keys in localStorage that are unique to each study.

**Review by jtlong3rd — APPROVED** [review]
Works great!

When the associated WDKClient work is merged and published to npm, you'll need to upgrade `web-eda`'s `@veupathdb/wdk-client` dependency as follows:

1. Run `yarn upgrade @veupathdb/wdk-client@latest`. This will automatically update the `web-eda` project's `yarn.lock` and `package.json` with the latest version of the `@veupathdb/wdk-client` `devDependency`.
2. Go into the `web-eda` `package.json` and manually alter the `@veupathdb/wdk-client` `peerDependency` to `>=<new version number of @veupathdb/wdk-client>`.

(The dependency on `@veupathdb/wdk-client` is specified in two ways: as a `devDependency` [which is is the version of `@veupathdb/wdk-client` which is used in the local dev environment] and a `peerDependency` [which is the version of `@veupathdb/wdk-client` which is expected to appear in the final site bundle]. We specify `@veupathdb/wdk-client` as a `peerDependency` instead of a regular `dependency` to prevent duplicate copies of `@veupathdb/wdk-client` from being bundled by our site.)

**Comment by jernestmyers** [comment]
Closes #810

**Pull request merged**
