### PR TITLE
Fix uncontrolled/controlled warning for Slider in HistogramFilter controls

### LINKED ISSUE #203: Material UI warning about controlled/uncontrolled props for Slider in HistogramFilter
I cannot reproduce this console warning in `web-components` storybook so I think it's an EDA issue with its usage of `Slider`.

Pretty sure I introduced this in the great tidy-up/controls refactor

### PR DESCRIPTION
**Pull request by bobular**
Fixes #203 

If there's a better way, I'd love to know.

### CODE REVIEW

**Review by jtlong3rd — APPROVED** [review]

**Review by dmfalke — COMMENTED** [review]
I'm wary of providing these "stub" values. I wonder if a better solution is to make sure the underlying widgets never use a value of `undefined`?

**Comment by bobular** [comment]
> I'm wary of providing these "stub" values. I wonder if a better solution is to make sure the underlying widgets never use a value of `undefined`?

I agree they are ugly and arbitrary.

If we hid the offending widget while the value was undefined, it would be OK, but then the layout would change and be distracting.

**Comment by dmfalke** [comment]
Okay, well let's go ahead with this solution for now. We can address in the future if something comes up.

**Review by dmfalke — APPROVED** [review]

**Comment by bobular** [comment]
> Okay, well let's go ahead with this solution for now. We can address in the future if something comes up.

We could put the stub values in the widget implementations, e.g. in web-components/src/components/widgets/Slider.tsx

```
      <MUISlider
        min={minimum}
        max={maximum}
        value={localValue ?? 0}
        step={step}
        onChange={handleChange}
      />
```
This keeps the problem at the lowest possible level.  Out of sight, out of mind!

**Comment by bobular** [comment]
Yeah, I've googled around some more, and everyone suggests "just use a fallback empty string" (e.g. `value={prop.foo ?? ''}`)

Not so good for number or slider inputs, but I will address this in a new PR in web-components.

**Pull request closed without merging**
