### PR TITLE
adding and styling viz title and subtitle

### PR DESCRIPTION
**Pull request by moontrip**
viz subtitle indicating plot, e.g., Scatter plot, is added and title and subtitle are styled according to the example shown by @dmfalke [here](https://github.com/VEuPathDB/web-eda/issues/154)

Here is a screenshot: text color for subtitle is #333333

scatter-subtitle-333333

### CODE REVIEW

**Review by jtlong3rd — APPROVED** [review]

**Review by jtlong3rd — APPROVED** [review]

**Comment by moontrip** [comment]
well sorry @jtlong3rd to make this review again and again. Some were my mistakes and the other one was added by automatic styling :( Thanks 👍

**Review by dmfalke — CHANGES_REQUESTED** [review]
When I recommended the current styling, I had forgotten about the editable analysis name at the top of the page. It is italicized and not bold. I think we should be consistent. ~Could you also make that non-italicized and bold?~ Thanks!

After another think, I think we should actually keep the analysis name as-is, and change the viz name back to that style. The subtitle can be non-italicized.

**Comment by dmfalke** [comment]
image

**Comment by moontrip** [comment]
@dmfalke I have made changes: actually removed some unnecessary styling :)

scatter-subtitle2

**Review by jtlong3rd — APPROVED** [review]

**Review by dmfalke — APPROVED** [review]

**Pull request merged**
