### PR TITLE
Partially address histogram bin width UI bugs

### LINKED ISSUE #1450: Visualizations: histogram/lineplot zooming should re-bin unless binWidth has been entered
Study: India ICEMR Cohort
Filters: Fever in last 48 hours = YES

On QA currently the behaviour is:

Make a **new** viz histogram of **temperature** 
Click "Auto-zoom".
Notice no spinner and no new back end request.

The behaviour should be that the binning should be re-done, based on the data, UNLESS a binwidth has been manually inputted by the user.

### PR DESCRIPTION
**Pull request by bobular**
Resolves #1450 
(which also has QA notes)

Works partially toward https://github.com/VEuPathDB/web-eda/issues/1443 and https://github.com/VEuPathDB/web-eda/issues/1274

### CODE REVIEW

**Comment by moontrip** [comment]
@bobular Thank you for your work. IIRC, I made the change because I thought axis range throughout other Vizs purely controlled  what ranges are displayed in a plot, not related to data (e.g., data reloading).

**Comment by bobular** [comment]
Hi @moontrip - I made lineplot only use the "annotated binwidth" when in "Full" mode and also updated the data-getting dependencies so that a change from Full to Auto-zoom or Custom would trigger a new data request.  I think the behaviour is good now.  A good combination to test with is LLINEUP Cluster Randomized Trial - lineplot - x=Age, y=Hemoglobin.

I will not address the fact that the default bin width (in Full mode) is 4.23 which is outside the allowed bin width slider range.  I am explaining this on https://github.com/VEuPathDB/web-eda/issues/1274 in a minute.

**Comment by bobular** [comment]
PS. going to add the "only use annotated binwidth when in Full mode" to histogram!

**Comment by moontrip** [comment]
@bobular I could confirm that the things you mentioned worked fine 👍 I also saw your comments at the ticket so I will leave this PR as is for the time being before any decision is made. But I could have approved this 😃

**Comment by bobular** [comment]
> @bobular I could confirm that the things you mentioned worked fine +1 I also saw your comments at the ticket so I will leave this PR as is for the time being before any decision is made. But I could have approved this smiley

Thanks!  There's no UX discussion required for the changes made in this PR. So we could merge.  The thing that needs discussion is what to do when the response invalidates the user's binWidth choice. Currently we just outline it in red and do nothing. Re-sending a new request seems kind of clunky. Anway, discussion should be on #1274.

**Review by moontrip — APPROVED** [review]
@bobular Thank you for your explanation. Then I will approve then you can decide its fate 😄

**Comment by bobular** [comment]
Thanks @moontrip 

@dmfalke I'm not sure what to do about QA for these fixes.

The "viz histogram back end request trigger-dependencies fix" fixes an issue we've only recently introduced onto the qa site and nobody has noticed it. This fix reverts to previous live site behaviour.

There's improved behaviour to supplement DK's axis mode work (histogram and lineplot).  Switching from Full to Auto or Custom will trigger a new back-end request (which in some cases will be necessary to re-bin the smaller x-axis range, other times it will make no difference).

There's also a small fix related to pressing the axis range reset button in histograms (it now sets bin width to `undefined` which gives us the desired default behaviour at the slightly cryptic [line 1326](https://github.com/VEuPathDB/web-eda/blob/9f4a53f355bd474846751bf2c6a2833cb68c12e6/src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx#L1326). 

On reflection, I'll make an issue ticket that describes the thing I poorly described just above, with a way to reproduce it on QA currently.

**Pull request merged**
