### PR TITLE
hide no data control for mbio alphaDiv and abundance

### PR DESCRIPTION
**Pull request by moontrip**
This addresses https://github.com/VEuPathDB/web-eda/issues/1089. Initially I tried to make a new prop to conditionally control the option, however, I realized that it also depended on onShowMissingnessChange function. Thus, I have made a condition to show and hide it: only for boxplot and scatterplot Vizs.

It is hidden for mbio alphaDiv and abundance, while it shows for other apps, e.g., pass app, mbio distributions, mbio X-Y relationships, etc.

### CODE REVIEW

**Comment by asizemore** [comment]
Hey @moontrip ! Lovely!! Works great!

Two notes:
1. After some discussion, mbio would like to remove the no data toggle from all visualizations in any app. So instead of the logic centering around the computation type, can it instead be a flag for app type? Then only the pass app would have the normal no data toggle. This logic avoids having to hardcode something like "if project === 'microbiome'".
2. i expect solving this issue would be simpler after the viz refactor because within each app plugin we can just say if there should or should not be a no data toggle. 

courtesy tag @dmfalke

**Comment by moontrip** [comment]
@asizemore Thank you for your comments. I am not that clear of No.1 but eventually it can be achieved by viz refactoring as you mentioned in the No.2? BTW, I have slightly changed the condition in this PR so that it checks app type.

One question is whether I need to change other Viz under mbio like histogram (at distribution app), mosaic (counts and proportions app), etc. not to have that no data control as well?

**Comment by asizemore** [comment]
> One question is whether I need to change other Viz under mbio like histogram (at distribution app), mosaic (counts and proportions app), etc. not to have that no data control as well?

Yes please! Seems like we should be able to do that same check of if app type is pass or not (I saw the logic change you made - looks good!)

**Comment by moontrip** [comment]
@asizemore Thank you for your confirmation! 👍 I will do that

**Comment by moontrip** [comment]
@asizemore done! 😃

**Review by asizemore — APPROVED** [review]
Tested on mbio and clinepi backends. Looks great @moontrip !

**Comment by moontrip** [comment]
@asizemore thank you for your review! I will merge it later 👍

**Pull request merged**
