### PR TITLE
Decapitalize globally (mostly)

### PR DESCRIPTION
**Pull request by chowington**
Fixes https://github.com/VEuPathDB/web-eda/issues/330

This changes the MUI default of making certain text all caps, though it may be overridden by a component's individual theme context (even implicitly).

### CODE REVIEW

**Comment by chowington** [comment]
Blocked by https://github.com/VEuPathDB/web-components/pull/215

**Review by bobular — APPROVED** [review]
Looks great - I just tidied up a few things (reset buttons can be much less wide now) - removed some colons, histoviz control vertical layout, and removed the focus effect on range input labels.

Was easier to do than describe or add as suggestions!

**Comment by chowington** [comment]
@bobular Are the x and y axis controls supposed to look so different? In width, defaults, etc.

image

**Comment by bobular** [comment]
You're right and on my screen (at certain window sizes) it's even worse...
(India ICEMR Fever Surveillance)
Date variables in particular have the problem - maybe something to do with squeezing the extra units menu in?
image


Would you be able to fix it please?  If it behaves similarly to non-date numeric vars (e.g. below), that will be fine in my opinion 
image

**Comment by chowington** [comment]
I pushed something but I don't think I'm quite satisfied with it. It gives the x-axis div more room to grow, but the widgets within don't seem to be interested in the extra space. It looks better when the screen is smaller, as the x control gets more space than it used to. But my change as a side effect also adds space between the x and y controls when the screen is large, which breaks precedent. I don't think it's worth it right now to find a better solution, but I'm also willing to revert back to the above existing styling. @bobular What do you think?

Smallish screen

image

Large screen

image

**Comment by bobular** [comment]
I had a play and the problem seems to be with the date-based inputs - they are much narrower.
The following kind of works - though doesn't look great on very wide screens.

[diff.txt](https://github.com/VEuPathDB/web-eda/files/7315921/diff.txt)

**Pull request merged**
