### PR TITLE
dont startCase if string includes rRNA

### LINKED ISSUE #1257: Mbio downloads: extra spaces and capitalization getting added
Only observed in the downloads tab for 16S assay entities.

The entity name is "16S rRNA (V4) assays". Curious why some of the text is getting transformed to uppercase (the r in rRNA) and some extra spaces are appearing?

Screen Shot 2022-07-13 at 4 49 11 PM

### PR DESCRIPTION
**Pull request by asizemore**
Resolves #1257 

We're using [startCase](https://lodash.com/docs/) to transform the entity display names in the downloads buttons. Sometimes we have biological terms (such as rRNA) that we'll never want to be startCase-ed. In order to handle these terms we could either
1. Have some complicated logic that only startCases the non-biological words
2. Just don't startCase the whole entity name (implemented now until we have a decision on the real question... see below)

Which brings me to the real question - was startCase-ing in this case an intentional decision we made a while back? Maybe because buttons should always be startCase-ed? Or do we want the button text to match the case of the entity diagram (sentence case)?
@danicahelb @SheenaTomko maybe you remember?

### CODE REVIEW

**Comment by SheenaTomko** [comment]
I don't remember if this was intentional or not. I would be ok with it matching the entity diagram (sentence case)

**Comment by asizemore** [comment]
Interestingly, google and apple are on different sides of the text case [debate](https://medium.com/@jsaito/making-a-case-for-letter-case-19d09f653c98)

**Comment by dmfalke** [comment]
I don't think the client code should ever manipulate display text. This makes it more difficult to be consistent.

**Comment by asizemore** [comment]
@jernestmyers and @dmfalke  - i think only one of you is needed for review of this tiny PR 😄

**Review by jernestmyers — APPROVED** [review]

**Review by dmfalke — APPROVED** [review]

**Pull request merged**
