### PR TITLE
Show more for long list of variable names at Subsetting

### PR DESCRIPTION
**Pull request by moontrip**
This will address #815 

Previously, long list of variable names at Subsetting was treated by introducing Show/Hide more link, but it was targeted to multifacet variables only. Now it is extended to general variable that has more than three list.

Somehow, Kalifabougou Malaria Cohort is not available so I could not test the example case shown in the issue #815, however, I think that this change would work just fine.

### CODE REVIEW

**Comment by dmfalke** [comment]
One thing I noticed is that we are processing `providerLabel` three separate times in this component:
https://github.com/VEuPathDB/web-eda/blob/02ec541993b38f39296f33a6cdb56e10d22498df/src/lib/workspace/Variable.tsx#L40-L119. In all three cases, we are branching on the exact same logic, and we are processing in the exact same way. This should be factored such that we only do this once.

@moontrip I don't know if this is something you want to take on now. If not, we should address this soon, if only to avoid duplicate code. I think the reality is that we will not hit a huge performance penalty, unless we get a lot of successive renders of this component due to incoming props changing. I'm happy to help, if you decide to do it.

**Review by jtlong3rd — APPROVED** [review]
Aside from the `providerLabel` DRYing up that Dave indicated, this should be good to merge.

**Comment by moontrip** [comment]
Thank you for your reviews and comments, @dmfalke @jtlong3rd 👍 
Yes I noticed the repetition so I will think of DRYing up 😃

**Comment by moontrip** [comment]
@dmfalke and @jtlong3rd I have made changes to minimize repetition. It would be great if you review this again

**Review by dmfalke — APPROVED** [review]
This looks great, @moontrip!

**Review by jtlong3rd — APPROVED** [review]

**Comment by moontrip** [comment]
thank you for your quick reviews @dmfalke @jtlong3rd 👍

**Pull request merged**
