### PR TITLE
Adjust CSS to remove extra scrollbar in VariableList dropdown container

### PR DESCRIPTION
**Pull request by jernestmyers**
Addresses issue #926 to remove the extra scrollbar in viz tab variable selector container.

These CSS changes are supplemented by [a change in WDKClient](https://github.com/VEuPathDB/WDKClient/pull/194).

In summary, the CSS changes are as follows:
1. Remove `height: 60vh` from the `.EDAWorkspace-VariableList` and `.wdk-CheckboxTree` classes
2. Add `height: 100%` to the `.EDAWorkspace-VariableList` class
3. Add `flex-grow: 1` to the `.wdk-CheckboxTree` class (in [wdk-CheckboxTree.scss](https://github.com/VEuPathDB/WDKClient/blob/master/Client/src/Components/CheckboxTree/wdk-CheckboxTree.scss))

### CODE REVIEW

**Comment by dmfalke** [comment]
I don't think this is quite ready. There are two issues that should be addressed.

First, I think we want just the checkbox tree items to be scrollable, not the entire container:
image

I was able to make this work with a simple addition to the css:
image
image

Second, in **Browse and Subset**, we want to put a max-height on the `.Variables` container. I think `70vh` is a good starting point.
image

**Review by dmfalke — APPROVED** [review]
I think this is good to go!

**Comment by moontrip** [comment]
@jernestmyers I am curious if this works without updating wdk-client version at package.json? For peerDependencies it would be fine due to its condition, but what about devDependencies? Still 0.6.0 in there, not 0.6.6 in [this merged PR](https://github.com/VEuPathDB/WDKClient/pull/194)

**Comment by jernestmyers** [comment]
ACK! I just reflexively fired off merges without thinking about the revamp to dependencies. Thanks for pointing this out.

**Comment by moontrip** [comment]
haha no problem. As I said, I was just curious if there was a hidden magic to deal with it 😉

**Pull request merged**
