### PR TITLE
Input variables computation handling

### PR DESCRIPTION
**Pull request by chowington**
Fixes https://github.com/VEuPathDB/web-eda/issues/970
Blocked by https://github.com/VEuPathDB/web-eda/pull/974 and https://github.com/VEuPathDB/web-eda/pull/824

### CODE REVIEW

**Comment by moontrip** [comment]
@chowington thank you for your update and I will take a look at this tomorrow. By the way, I think that this PR should be merged into it's parent, initial-apps-run-update, not main branch? It is because the parent brach should be firstly merged with major updates before this PR.

**Comment by chowington** [comment]
Thanks DK! I certainly was planning on waiting for the parent branched to be merge before merging this one---I thought that might happen soon, but maybe not! I changed the base accordingly.

**Comment by moontrip** [comment]
@chowington I have tested this PR and overall it works fine. It is understandable that overlayVariable for scatter plot viz in the abundance app was not implemented due to the lack of the information we can get for now: it can probably be added later. I think that Dave needs to review this PR which means we need to wait for his comeback after vacation.

One minor comment is that the texts for computed variable (e.g., yAxisVariable for alphadiv app) seem to be smaller than others (I mean, other variable selector's title like X-axis and its selected variable, etc.).

**Comment by chowington** [comment]
Thanks for the comments @moontrip!

Can you give me a photo of the font size difference you're seeing? I'm not seeing it on my screen. They all have the same font size to me:

image

**Comment by moontrip** [comment]
@chowington oh! I thought Y texts were smaller than others, but was wrong probably due to: a) saw it at 4k screen without zooming; b) that gray pull-down menu at X-axis seemed to make me misread the size of Y-axis one. Sorry about that!

By the way, I am not quite sure whether `(fixed)` text is appropriate. I think it may be `(computed)` as well. Probably @asizemore can give a better idea of the word :)

inputselector

**Comment by asizemore** [comment]
@moontrip @chowington I think "(fixed)" is great! I do like "(computed)" as @moontrip suggested, but since not all of our fixed variables are computed variables (sometimes they come from collections without any computations being run), i think "(fixed)" is preferable because it can be generally applied.

**Review by dmfalke — APPROVED** [review]
This looks good! We might want to adjust the styling in the future, but we should get general feedback before spending too much time on it.

**Review by moontrip — APPROVED** [review]

**Pull request merged**
