### PR TITLE
Access Request Enhancements

### PR DESCRIPTION
**Pull request by chowington**
Works toward https://github.com/VEuPathDB/web-eda/issues/1150

### CODE REVIEW

**Comment by jernestmyers** [comment]
Can I get clarification on testing this work? I'm getting a `Page Not Found` when I try to log in from the "request access" link. Of possible interest: I'm running a local dev server with your branch.

image

**Comment by chowington** [comment]
> Can I get clarification on testing this work? I'm getting a `Page Not Found` when I try to log in from the "request access" link. Of possible interest: I'm running a local dev server with your branch.
> 
> image

Yep! You should test by running a full clinepi website as I describe in this comment: https://github.com/VEuPathDB/web-study-data-access/pull/23#issuecomment-1424836018

FYI there are three PRs dealing with the ticket above, so it might be best to wait until I undraft all of them before testing. Here are the other two:
https://github.com/VEuPathDB/ClinEpiWebsite/pull/76
https://github.com/VEuPathDB/web-study-data-access/pull/25

**Comment by chowington** [comment]
All undrafted, @jernestmyers!

**Comment by jernestmyers** [comment]
I notice that if I click to log in, it's behind the modal and I can't log in unless I close the access request modal. I'd expect the access request modal to either close or have a lower zIndex such that I can login.

This may be out of the scope of this ticket, but maybe not? 

image

**Review by jernestmyers — APPROVED** [review]
I'm going to approve this so it's not blocked, though I'm still curious about that popup behavior. All other testing seemed okay except for one other oddity, that I think may (also) be unique to our dev environments.

Basically, if I click the "request access" link and enter my credentials that have site-wide access, I'll see a very brief flashing of an error modal as I get logged in. I couldn't find any meaningful error messages in the Network tab or console though.

**Pull request merged**
