### PR TITLE
Input variable clear button

### PR DESCRIPTION
**Pull request by chowington**
Fixes https://github.com/VEuPathDB/web-eda/issues/1042
Requires https://github.com/VEuPathDB/CoreUI/pull/117

### CODE REVIEW

**Review by jernestmyers — COMMENTED** [review]
This is looking great! The mockups suggest we'd also like this functionality in the line plot's proportion controls, but I'm not seeing it implemented yet in your branch.

image

**Comment by chowington** [comment]
> 

Good catch! Done 👍

**Review by jernestmyers — APPROVED** [review]
Looks good, and I'm looking forward to the merge conflicts from when I pull this work into my branch that replaces these variable selectors!

**Comment by chowington** [comment]
> Looks good, and I'm looking forward to the merge conflicts from when I pull this work into my branch that replaces these variable selectors!

:) Thanks, and good luck future Jeremy!

**Pull request merged**
