### PR TITLE
updates on scatter plot viz and InputVariables component

### PR DESCRIPTION
**Pull request by moontrip**
For InputVariables component: removed border and text (Data Inputs)

Note that this requires the merge of [the corresponding PR at web-components](https://github.com/VEuPathDB/web-components/pull/125) 

For scatter plot viz:
a) adjusted plot control to the button text with spaces
b) made colors up to 10: previously only two colors were manually set, which caused some issue with overlay variable more than 2 stratifications. Those colors are taken from plotly's default colors - screenshot attached
c) some minor changes

scatterplotviz1

### CODE REVIEW

**Review by bobular — COMMENTED** [review]
Looks good DK - please merge after removing commented out lines of code and the DKDK comments.

**Comment by moontrip** [comment]
> Looks good DK - please merge after removing the DKDK comments.

@bobular Thank you for your review. Yep I had a plan to clean things up :)

**Comment by bobular** [comment]
No need to have just the 'Data" legend item - skip the legend altogether in this case?
image

**Comment by moontrip** [comment]
> No need to have just the 'Data" legend item - skip the legend altogether in this case?
> image

@bobular actually it was already addressed in this PR following your approach at histogram like disabling legend for single dataset, i.e., raw data without overlay 

https://github.com/VEuPathDB/web-eda/blob/2b88d0ed209e3fede57a8b7cacf461d69ae68365/src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx#L415

**Comment by moontrip** [comment]
adopted data API changes for scatter plot for now. However, I realized that the API doc had a couple of incorrect info based on the actual response from the backend. I have discussed with Danielle and she said there were incorrectness at both the doc and the backend. Accordingly, additional changes would be required in the near future.

**Comment by moontrip** [comment]
Adopted additional data API change due to incorrect responses from backend. Also implemented empty plot and plot control for no data or data error. Screenshots are attached

scatter-empty2
scatter-empty1

**Comment by moontrip** [comment]
scatter plot component at web-component repo is renamed to XYPlot, thus scatter plot viz is also changed to use the new component name, XYPlot

**Comment by moontrip** [comment]
With the merge of corresponding [PR](https://github.com/VEuPathDB/web-components/pull/125) at web-component repo, @veupathdb/components version is update and scatterplot viz is changed to use XYPlotControls

**Review by bobular — APPROVED** [review]
Looks good to merge :-)

My only suggestion (for the future) is that we shouldn't have colour palette code in each visualization - it needs to be centralised somehow.

Thanks!

**Comment by moontrip** [comment]
Many thanks for your review, @bobular 👍 I will merge this PR.

I agree with your opinion concerning the color palette. Perhaps we can load it at each plot viz if it is stored at a central place as you suggested :)

**Pull request merged**
