### PR TITLE
@veupathdb/components upgrade(s) for ticket #872

### LINKED ISSUE #872: Browse and subset tab: Remove extra x-axis values on histogram when very few values available; and erroneous red outlining of binwidth input
Danielle made changes to the use of datashape, so now numeric and date variables that have <10 values are shown using a histogram in the browse and subset tab. This works well until you get down to very few values that are clustered together. In cases like the one below (study = PROMOTE, variable = Placenta count), where there are just 2-4 potential values, you see extra values on the x-axis indicating 0.5, 1.5, etc. that make it look like there are might be more bars there, for instance 2 bars of equal height at 1 and at 1.5. In cases like this, we'd like to reduce the number of values shown on the x-axis to avoid this issue.

Screen Shot 2022-02-09 at 12 46 51 PM

Note for QA testers. I @bobular have combined another minor bugfix along with the original bug. It is described here: https://github.com/VEuPathDB/web-eda/issues/1274#issuecomment-1265309212

> I'm also noticing that the bin width slider box turns red (but with no other warning) when the bin width is set to either of the extremes of the allowed range.

(note that this happens with text input - slider input is subtly different, but also buggy)

image

### PR DESCRIPTION
**Pull request by bobular**
Resolves #872

### CODE REVIEW

**Comment by moontrip** [comment]
@bobular do you need an approval of this? If so I can approve it

**Review by moontrip — APPROVED** [review]

**Comment by bobular** [comment]
Thanks @moontrip - just waiting for a merge from Connor before I can update this and merge it.

**Comment by moontrip** [comment]
@bobular yep I confirmed with @chowington about this as I also need to do similar thing for my merged PR at web-components: realized you already did versioning so I wanted you to merge this at first 👍

**Comment by bobular** [comment]
I can always re-version. Go ahead and merge your stuff if you need to.
(I'm working on mock-ups at the moment.)

**Comment by moontrip** [comment]
@bobular ok I see. Then, I will try to merge mine first.

**Comment by moontrip** [comment]
@bobular I have merged mine (https://github.com/VEuPathDB/web-eda/pull/1473) so please update yours later 👍

**Comment by bobular** [comment]
A [previous merged PR](https://github.com/VEuPathDB/web-eda/pull/1473/files) has already upgraded @veupathdb/components to a version higher than required here but I'm incrementing a web-eda version anyway.  I could also just have deleted this PR, I think!

**Pull request merged**
