### PR TITLE
Fixes to map marker overlay issues

### LINKED ISSUE #1419: Map viz and FSM overlay bugs
- [ ] binning for the continuous overlay vars in the maps is not being set from the client correctly

the `binSpec` in the request is empty - I know why and am fixing it.

There's no glaring issue to the user, but the binning should always span the variable's range (not what's in the response), and currently it doesn't (try subsetting on the continuous variable and see the binning change)

- [ ] some categorical variables in the vectorbase megastudy are causing 500 for the `map-markers-overlay` endpoint

@dmfalke hit a bug where map-markers-overlay returned a 500, but the client didn't handle it well: https://feature.vectorbase.org/vectorbase.feature/app/workspace/analyses/DS_4b8cb8bb2e/new, open map and overlay by Sample
image

### PR DESCRIPTION
**Pull request by bobular**
Resolves #1419 

- [x] binning
- [x] 500 from overlay endpoint
- [x] set a more sensible FSM default zoom level

### CODE REVIEW

**Comment by bobular** [comment]
I'd greatly appreciate it if someone could put the `PluginError` banners on top of the map instead of shunting it down. :pray:

**Review by dmfalke — APPROVED** [review]

**Review by dmfalke — COMMENTED** [review]
I hastily approved this. I can play with the placement of the error message.

**Comment by dmfalke** [comment]
I pushed a change to update the position of the error message. If you're happy with it, feel free to version and merge.

image

**Comment by bobular** [comment]
Thanks @dmfalke ! Looks great. I really must learn some basic layout one of these days 😉

**Pull request merged**
