### PR TITLE
Re-enable lineplot and map in pass.tsx

### PR DESCRIPTION
**Pull request by bobular**

### CODE REVIEW

**Review by moontrip — APPROVED** [review]
Thank you for taking care of this! 👍

**Review by dmfalke — APPROVED** [review]

**Comment by bobular** [comment]
Oops - merged before I saw this and I didn't do a version update ...

**Comment by dmfalke** [comment]
Oh, I see you already merged. No worries!

**Comment by dmfalke** [comment]
I will do a version update :)

**Comment by bobular** [comment]
Sorry and thanks.

**Comment by dmfalke** [comment]
No worries.

**Pull request merged**
