### PR TITLE
Variable Constraints Documentation

### PR DESCRIPTION
**Pull request by d-callan**
thought id make a PR just as a place to discuss.. i wonder primarily:

1. if there is anything else we need to add/ update (@danicahelb @asizemore others?) 
2. if we can talk about the styling of this document. i have this general feeling it could be improved but no specific feedback.. (@asizemore @eikonomega others?)

### CODE REVIEW

**Comment by d-callan** [comment]
actually another question.. if mbio plans to use this page as well, do we want clinepi in the title?

**Comment by asizemore** [comment]
In terms of styling, i think the simplicity is nice. The only thing i'd consider adding is a line or two to break up the page. Specifically between the tldr and the rest of the page. 

Larger margins on the left and bottom would be a big help i think, and keep this [page](https://beta.clinepidb.org/ce.beta/app/workspace/analyses/documentation/variable-constraints) more consistent with other help [pages](https://qa.clinepidb.org/ce.b19/app/static-content/ClinEpiDB/tutorials.html). I'd also try making the plot titles h3 instead of h2, and increasing the paragraph text size a tad.

**Comment by d-callan** [comment]
@dmfalke thoughts on making this page available under the help tab as well? is that all static content stuff?

**Comment by d-callan** [comment]
resolves #575

**Review by dmfalke — APPROVED** [review]

**Pull request merged**
