### PR TITLE
changing padding truncation logic

### PR DESCRIPTION
**Pull request by moontrip**
This will address #1015  with corresponding web-components PR, https://github.com/VEuPathDB/web-components/pull/346. Now, axis ranges shown in the input fields reflect data or metadata min/max, not including padding/margin value.

- changes
a) Tried to minimally change web-eda's Vizs, so key changes are made at web-components.
b) Padding/margins are decreased as requested
c) Also fixed a bug at boxplot concerning dependent axis range.
d) Also addressed #1076 in this PR. (see the second screenshot)
e) For histogram and barplot, I did not make padding/margin for dependent axis's min as it is typical in those plots. Not quite sure if I should have set this to boxplot as well.
f) truncations are also considered
g) and more stuff which I might have forgotten to say :)

For a comparison purpose and an example, below are two screenshots with GEMS1 case control and same X/Y variables. First one is taken from qa site and the other one is taken with this PR. One can see that both independent and dependent axis ranges show data's (or metadata's) min/max, not including padding/margin values.

## qa site
scatter-padding-qa

## this PR
scatter-padding

## this PR and truncations for demo purpose
scatter-padding-truncation

### CODE REVIEW

**Review by jtlong3rd — APPROVED** [review]

**Comment by moontrip** [comment]
@jtlong3rd Thank you for your review and approval PRs at both web-eda and web-components.
I have addressed another issue in this PR, #1098. Some CSS values, etc. are changed but basically not much changes are made from the programming sense: this also includes histogram filter at Subsetting. Not clearly hear the answer for the case of Y-axis range controls only (asking Danica), but I presumed that it required to have spaces so that it is located in the right side (screenshot). If we don't need the space, I will change it accordingly.

Here are screenshots. 
scatter-XY-position

boxplot-XY-position

**Comment by moontrip** [comment]
Additional ticket is addressed in this PR, #589 at https://github.com/VEuPathDB/web-eda/pull/1102/commits/65f53ad6460726d42694016506ed1f0d1200ab41. It is basically to set the dependent axis range for histogram filter at Subsetting so that its log scale shows from 0. 

While doing this, I also found a bug for the original padding/margin work so will address it as well.

Here are two screenshots taken from qa site and this PR for a comparison purpose.

### qa site
qa-histogram-filter-logscale

### current PR
dev-histogram-filter-logscale

**Comment by dmfalke** [comment]
Hi @moontrip, nice work with this. I think it's great that you are addressing so many issues, but I think it might make sense to make new PRs for the other two issues, rather than reusing this one. @jtlong3rd has already approved the initial issue being addressed, so that work could be merged. If there are issues with the subsequent issues being addressed.

Is this something you would feel comfortable doing? This is what I would do:

- Make a new branch from this one, and make a PR for the other issues being addressed.
- In this branch, drop the commits, starting with https://github.com/VEuPathDB/web-eda/pull/1102/commits/827e3d8d8c8cbc6a278a0ff09b815b09f54541ed: `git reset --hard 75add6f` should do it.
- Once this PR is merged, update the new branch from `main`.

**Comment by moontrip** [comment]
> Hi @moontrip, nice work with this. I think it's great that you are addressing so many issues, but I think it might make sense to make new PRs for the other two issues, rather than reusing this one. @jtlong3rd has already approved the initial issue being addressed, so that work could be merged. If there are issues with the subsequent issues being addressed.
> 
> Is this something you would feel comfortable doing? This is what I would do:
> 
> * Make a new branch from this one, and make a PR for the other issues being addressed.
> * In this branch, drop the commits, starting with [827e3d8](https://github.com/VEuPathDB/web-eda/commit/827e3d8d8c8cbc6a278a0ff09b815b09f54541ed): `git reset --hard 75add6f` should do it. You will need to do `git push --force-with-lease` after this.
> * Once this PR is merged, update the new branch from `main`.

@dmfalke Thank you for your advising. Yes normally I won't do like this, but somehow those issues are similar to each other and I was waiting for Bob's response: certainly I can merge with Jamie's approval only for sure 😄

One minor issue is that I found a bug at the originally approved PR and it would probably fixed at the corresponding web-components (WIP) so I will follow your suggestion after fixing it in there: the other works are done in the web-eda so it would be more convenient to fix it and then merge the PR.

**Review by bobular — COMMENTED** [review]
Hi - sorry for taking a while to get to this.

I haven't tracked down the lines of code yet, but I noticed that lineplot with a date-based x-axis variable, when binned (e.g. 1 year), no longer has any padding at the left (and very tiny amount on the right).

GEMS1: diarrhoeal episode duration vs birth date
Old/main:
image

New/this branch:
image

**Comment by bobular** [comment]
> Hi - sorry for taking a while to get to this.
> 
> I haven't tracked down the lines of code yet, but I noticed that lineplot with a date-based x-axis variable, when binned (e.g. 1 year), no longer has any padding at the left (and very tiny amount on the right).

Looks like Lineplot.tsx is using `extendAxisRangeForTruncations` - so maybe the Date Math is rounding to zero or something?

**Comment by moontrip** [comment]
@bobular Thank you for your tests. Although I think you already did, but Just in case please note that this PR relies on web-components's PR, https://github.com/VEuPathDB/web-components/pull/346, so you should use yarn link. 

The reason why I am checking above is that I can actually see correct behavior with your example at my local dev. Below is my screenshot.

lineplot-birthDate

**Comment by bobular** [comment]
Duh I am sorry @moontrip - I turned off yarn link due to the troubles earlier.  And obviously forgot to put it back on.

Works fine then.  Have already looked through the code - will approve.
image

**Review by bobular — APPROVED** [review]
Looks good. Glad it wasn't as tricky as we feared.

**Comment by moontrip** [comment]
> Looks good. Glad it wasn't as tricky as we feared.

@bobular Glad it was not an issue! 😄 To reach that solution, I had to check several other logics 😄 Thank you for your reviews/test/approval! 👍

**Pull request merged**
