### PR TITLE
Faceted plot styling

### PR DESCRIPTION
**Pull request by dmfalke**
refs #635 and https://github.com/VEuPathDB/web-components/issues/240
depends on https://github.com/VEuPathDB/web-components/pull/252

This PR is primarily focused on the styling of plots when they are used with `FacetedPlot`. Eventually, some of this work may be moved to web-components as variants of `FacetedPlot` (e.g., `FacetedHistogram`, etc).

Not, there are potentially some issues with ticks (definitely with mosaic). Any tips for how to address this would be great, but I can try to figure it out myself.

ETA I also threw in an ordering on the studies list.

### CODE REVIEW

**Comment by moontrip** [comment]
@dmfalke Thank you for your info! 👍 I have briefly tested some cases but it seems to me that smaller size of faceted plots (half of normal plot) causes some issues for categorical data having lengthy texts, e.g., Floor material, etc. Certainly I believe you would address it but I doubt shorter ellipsis may not be sufficient for such cases. Here is an example screenshot. (GEMS1 Case Control)

barplot-floor-material

**Comment by dmfalke** [comment]
Thanks for the feedback, @moontrip. I'm not really sure how best to address this. I will try by using a shorter length. I'm not really sure what other options we have.

**Comment by dmfalke** [comment]
Another option is to make the plots taller. I will do that first, since it's easier

**Comment by dmfalke** [comment]
I'm having a lot of trouble with mosaic
image

**Review by jtlong3rd — APPROVED** [review]
The code looks solid! 🤞 that the long categorical data label issue isn't too tricky to resolve.

**Comment by bobular** [comment]
> I'm having a lot of trouble with mosaic

What's the problem?  The overlapping tick labels?

**Comment by dmfalke** [comment]
I just pushed a commit that makes the subplots taller, which handles the long tick labels.

@bobular yes, I'm referring to the overlapping tick labels. However, I see this is not unique to faceting, so I guess we can kick the can down the road a bit longer.

**Review by jtlong3rd — APPROVED** [review]

**Pull request merged**
