### PR TITLE
banner spacing for Vizs

### PR DESCRIPTION
**Pull request by moontrip**
This will address https://github.com/VEuPathDB/web-eda/issues/1502 and https://github.com/VEuPathDB/web-eda/issues/1503, but the latter, Lineplot Viz is still in progress, thus this is currently a draft PR. Note that this relies on https://github.com/VEuPathDB/CoreUI/pull/131. 

**UPDATE 1: now CoreUI version (https://github.com/VEuPathDB/CoreUI/pull/131) is up so no dependency requires**
**UPDATE 2: due to adding timeout, this PR now relies on https://github.com/VEuPathDB/CoreUI/pull/134**

When https://github.com/VEuPathDB/web-eda/issues/1503 is ready, this PR will be switched to a regular PR.

Some screenshots with a Scatterplot Viz are shown in the following:
scatter-log-banner0

scatter-log-banner1

### CODE REVIEW

**Comment by moontrip** [comment]
Lineplot Viz now has banner instead of snackbar. A screenshot is attached:

lineplot-banner

**Review by bobular — COMMENTED** [review]
It looks great, but it's implied that the expanded message should never take up more than two lines.  If there's a longer `additionalMessage` (as I have simulated below for scatterplot) then there are some layout problems. I assume this can be handled with `min-height` rather than `height` but I haven't looked into the CSS at all.

image

I tried to test in Lineplot and found a [bug](https://github.com/VEuPathDB/web-eda/issues/1523) with categorical x-vars - that is not present in `main` - but I assume a merge from main will fix that.

Testing lineplot with non-categorical x-variables: the banners work fine, but the temporary nature of the snackbars was a good thing. Now they hang around until either a) the offending toggle has been reversed (e.g. cancelling y-axis logscale gets rid of "Error bars are no longer appropriate and have been disabled") or b) creating a banner from the other axis, and then reverting the toggle so that message disappears.

It seems a bit inconsistent.  Could we consider timeouts?  I'll add a topic for Wednesday.

**Comment by bobular** [comment]
Yes, that all sounds wise!

**Comment by moontrip** [comment]
@bobular I have updated this banner work, which now has timeout: currently it is set to be 5 sec (5000 ms). It would be great if you can re-review this. Also changed styles as we discussed before.

**Comment by chowington** [comment]
Hi @moontrip and @bobular, I reviewed the timeout change and I think it works for the line plot's log scale/error bar case, but it's not appropriate for the scatter plot's smoothed mean/best fit line/log scale case. That settings combination causes the plot to not show up until the settings are changed, so the content message needs to stay rather than disappear so the user always knows why the plot isn't showing up

**Comment by moontrip** [comment]
@chowington Thank you for your observation! As discussed in yesterday meeting, we won't use banner timeout for Vizs, so banner will always show up. For banner component itself (CoreUI), I think we can keep because it it is am additional feature for banner.

**Comment by chowington** [comment]
Ok, that sounds good, DK!

**Comment by moontrip** [comment]
@bobular I have updated this PR by addressing the feedbacks from Danica and you. Since the corresponding CoreUI work was merged, this PR no longer needs to use npm-pack-here. 

Here are screenshots (GEMS1 lineplot viz):

- vertically centered when only one banner exists (your request at Slack, https://epvb.slack.com/archives/C0132PM1MT5/p1671190173467599?thread_ts=1671053277.443879&cid=C0132PM1MT5 😃)
lineplot-banner1

- two banners (Danica's request) - banner messages are changed following https://github.com/VEuPathDB/web-eda/issues/1503#issuecomment-1353693069
lineplot-banner2

**Review by chowington — APPROVED** [review]
Looks great, @moontrip!

**Comment by moontrip** [comment]
@chowington thank you for your tests and reviews! 👍

**Review by bobular — CHANGES_REQUESTED** [review]
One tiny issue: the plot controls seem to shift downwards by one pixel (Firefox, Linux) when the second banner is displayed for lineplot. They may need a tiny bit more space or less padding.

One larger issue: the behaviours of scatterplot and lineplot are not consistent.

Scatterplot, which I believe has the correct/desired behaviour: user makes a "mistake" the banner is shown, no plot is shown, the banner goes away when the user corrects their mistake.

Lineplot is currently allowing the user to make a mistake, another toggle is changed to compensate, and a banner is shown. That banner can be removed by clicking again on the last toggle, but the user already has a plot in front of them and may not want to change the plot they already have.  (I understand that fixing this is possibly more than "low cost", though I see that #1503 doesn't have a cost.)

Also, with Scatterplot, when I ask for x-axis logscale I get the "Data may have been truncated" warning, which is a bit misleading because there is no data nor are there any yellow warning bars.

image

**Comment by bobular** [comment]
> Also, with Scatterplot, when I ask for x-axis logscale I get the "Data may have been truncated" warning, which is a bit misleading because there is no data nor are there any yellow warning bars.

Hi @moontrip 

I looked further into this minor issue. I guess it is something we didn't catch from the previous work on this functionality, not the current PR.

I see a few minor code issues: one is that `showLogScaleBanner` is a dependency of the `data = usePromise` but is not used inside that block.  Instead there's a bit of [code duplication](https://github.com/VEuPathDB/web-eda/blob/9de12ab715ef2d4232c4d1e8703d1e4a0781cb2c/src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx#L501-L506).  It would be good to use `showLogScaleBanner` here instead.

For a quick fix we can probably add `&& !showLogScaleBanner` to the condition at https://github.com/VEuPathDB/web-eda/blob/9de12ab715ef2d4232c4d1e8703d1e4a0781cb2c/src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx#L1519   or maybe even the more generic `&& data != null` which would handle more cases.

**Comment by moontrip** [comment]
> > Also, with Scatterplot, when I ask for x-axis logscale I get the "Data may have been truncated" warning, which is a bit misleading because there is no data nor are there any yellow warning bars.
> 
> Hi @moontrip
> 
> I looked further into this minor issue. I guess it is something we didn't catch from the previous work on this functionality, not the current PR.
> 
> I see a few minor code issues: one is that `showLogScaleBanner` is a dependency of the `data = usePromise` but is not used inside that block. Instead there's a bit of [code duplication](https://github.com/VEuPathDB/web-eda/blob/9de12ab715ef2d4232c4d1e8703d1e4a0781cb2c/src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx#L501-L506). It would be good to use `showLogScaleBanner` here instead.
> 
> For a quick fix we can probably add `&& !showLogScaleBanner` to the condition at
> 
> https://github.com/VEuPathDB/web-eda/blob/9de12ab715ef2d4232c4d1e8703d1e4a0781cb2c/src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx#L1519
> 
> or maybe even the more generic `&& data != null` which would handle more cases.

Thank you for your identifying this, Detective! 😃 I will look at them next week.

**Comment by bobular** [comment]
> DK: It may be more UI/UX discussion before taking an action. But Danica wanted to keep showing a banner if user does not fix it and stacking banners (X and Y). So I think that current behavior is what she wants?

I'm not sure that's exactly what she wants, but I've asked for clarification here:

https://github.com/VEuPathDB/web-eda/issues/1503#issuecomment-1373960117

**Comment by moontrip** [comment]
@bobular I have tested your findings and tried to fix them: a) linux firefox spacing: I could check it out so I have added a bit more spacing, so it seems to be resolved for me; b) truncation warning: yes it left a truncation warning in some cases. Thus, I have added `data.value != null` (`data != null` was not sufficient) condition at https://github.com/VEuPathDB/web-eda/blob/9de12ab715ef2d4232c4d1e8703d1e4a0781cb2c/src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx#L1519

**Review by bobular — APPROVED** [review]
Hi @moontrip 
I have removed the "resolves 1503" so we can address the behavioural issue when Danica gets back to us (though I'm pretty sure she'll want no plot when the user has selected an illegal combination). Currently she has more important things to worry about (in California).

The truncation stuff works great now, and the spacing seems fine in my FF. Thanks!

**Comment by moontrip** [comment]
@bobular Thank you for your review and tests 👍 Yes, if that no plot is needed, then we can probably handle it at new ticket.

**Pull request merged**
