### PR TITLE
Mosaic table view

### PR DESCRIPTION
**Pull request by chowington**
Fixes https://github.com/VEuPathDB/web-eda/issues/237
Depends on https://github.com/VEuPathDB/web-components/pull/179

Waiting on decision regarding tabs vs showing both views side-by-side
Update: decision made to go with tabs

### CODE REVIEW

**Review by bobular — APPROVED** [review]

**Comment by dmfalke** [comment]
@chowington please update references to issues such that they are not automatically linked. Thanks!

**Review by moontrip — APPROVED** [review]

**Comment by chowington** [comment]
Waiting on review from @jtlong3rd and @dmfalke

**Review by dmfalke — APPROVED** [review]
Sorry for the delay! I approved the companion PR in web-components. I just missed this side of the coin.

**Comment by jtlong3rd** [comment]
> Sorry for the delay! I approved the companion PR in web-components. I just missed this side of the coin.

Same here! 😆 Sorry about that, @chowington .

**Review by jtlong3rd — APPROVED** [review]

**Comment by chowington** [comment]
No prob all! :)

**Pull request merged**
