### PR TITLE
scatterplot Viz banner, behaviors, etc.

### PR DESCRIPTION
**Pull request by moontrip**
This will address scatterplot Viz works: https://github.com/VEuPathDB/web-eda/issues/1423 and https://github.com/VEuPathDB/web-eda/issues/1424.

Screenshots are:
- banner for no smoothed mean
scatter-banner1

- when pressing Why? at banner
scatter-banner2

- log scale and smoothed mean/best fit (no plot is drawn as requested)
scatter-banner3

- when pressing Why? at banner
scatter-banner4

### CODE REVIEW

**Review by bobular — APPROVED** [review]
Works great!

Tricky to reproduce though. Here's how I did it:
PRISM2 ICEMR Cohort -> no filters -> Scatter -> x = age, y = market distance, overlay = wall material

I personally have a problem with the logscale behaviour. The logscale toggle button moves across the screen after I select it (because its label changes, not as part of this work, I know). So when I've been "naughty" and turned on logscale, I don't want to have to hunt for the logscale toggle again, I just want to click again in the same place to turn it off.

I'll approve anyway because maybe that's a topic for UX discussion @danicahelb - and this PR looks solid.

Also @danicahelb - are we going to make Lineplot consistent? It currently uses snackbars to inform the user that logscale wasn't appropriate (and gets switched off) when error bars were switched on.

Also the moving logscale toggle annoys me in lineplot too!

**Comment by moontrip** [comment]
@bobular Thank you for your reviews and tests 👍

**Comment by moontrip** [comment]
> Also @danicahelb - are we going to make Lineplot consistent? It currently uses snackbars to inform the user that logscale wasn't appropriate (and gets switched off) when error bars were switched on.

@bobular yes Lineplot Viz is currently using snackbars for log scale stuffs as a part of the previous ticket, https://github.com/VEuPathDB/web-eda/issues/1291 where both Scatterplot and Lineplot Vizs were dealt with. As you said, it may be better to have a consistent UI for this too.

**Comment by danicahelb** [comment]
@bobular we discussed your issue about needing to change your mouse position in the 12/2/22 eda ux meeting. I made these 2 tickets to address this:
https://github.com/VEuPathDB/EdaNewIssues/issues/497
https://github.com/VEuPathDB/EdaNewIssues/issues/496

**Comment by danicahelb** [comment]
@bobular @moontrip we also discussed the inconsistency in line plots with the snackbar. i made this ticket to address that: 
https://github.com/VEuPathDB/EdaNewIssues/issues/498

**Pull request merged**
