### PR TITLE
Default variable behavior

### PR DESCRIPTION
**Pull request by dmfalke**
This PR includes
* Better selection of default variable when an entity is selected. It is now based on the tree structure of the variables.
* Automatically collapse inactive entities in the variable tree, while retaining the expansion state of internal nodes. This way the user can go back and forth between entities without losing expansion state.

### CODE REVIEW

**Comment by moontrip** [comment]
@dmfalke I have tested this and mostly works fine as described. One minor thing I notice is the "expand all" feature on top of the variable tree functions does not work correctly: it always expands the first Entity only (Household in this case) regardless where the selected variable is. Simply put, it does not expand all :)

**Review by bobular — APPROVED** [review]
Have reviewed/understood all the changes.  Apart from the SCSS which I will need to read up on.

**Comment by dmfalke** [comment]
> @dmfalke I have tested this and mostly works fine as described. One minor thing I notice is the "expand all" feature on top of the variable tree functions does not work correctly: it always expands the first Entity only (Household in this case) regardless where the selected variable is. Simply put, it does not expand all :)

Thanks for the review, @moontrip. I'm aware of this issue. I should have added a note to the description. I think I want to get some UX related feedback on this. I think the "expand all" feature is incompatible with the notion of collapsing other entities, but others may have ideas on this. Feel free to make suggestions in the comments.

**Comment by moontrip** [comment]
> > @dmfalke I have tested this and mostly works fine as described. One minor thing I notice is the "expand all" feature on top of the variable tree functions does not work correctly: it always expands the first Entity only (Household in this case) regardless where the selected variable is. Simply put, it does not expand all :)
> 
> Thanks for the review, @moontrip. I'm aware of this issue. I should have added a note to the description. I think I want to get some UX related feedback on this. I think the "expand all" feature is incompatible with the notion of collapsing other entities, but others may have ideas on this. Feel free to make suggestions in the comments.

Honestly, I am not quite sure whether the feature, expand all, is that important part of the tree view, especially with lots of sub-trees and variables inside: on the contrary, collapse all may be useful and it works well. This was the reason why I said 'minor thing' :)

**Comment by bobular** [comment]
I should add that I didn't actually test the branch!

**Comment by dmfalke** [comment]
I spoke with @aurreco-uga about the "expand all" issue. The conclusion is to only collapse other entities when navigating externally (e.g., click a box in the entity diagram).

**Pull request merged**
