### PR TITLE
adding Scatter plot control at viz

### PR DESCRIPTION
**Pull request by moontrip**
This adds the plot control of the data selection (raw, smoothedMean, smoothedMeanWithRaw, and bestFitLineWithRaw). To make this work, the other PR at web-component repo, [Making Scatter plot controls](https://github.com/VEuPathDB/web-components/pull/121), needs to be approved and merged:  failed check at github CI is related to this.

A screenshot is added, just in case

scatterWithControl-bestFit1

### CODE REVIEW

**Comment by moontrip** [comment]
@dmfalke I have added a draft of densityplot in this branch as well. The reason why I say "draft" is that I did/could not test the densityplot because I realized that the densityplot API is not working yet: confirmed with Danielle and she said it would be phase 2. 

Accordingly, I did not activate "densityplot" at PassThroughComputation component. However, I confirmed that the other viz, scatterplot and lineplot vizs, are working correctly, regardless of the addition of the densityplot. thus, I opine that we can keep this densityplot draft anyway.

**Comment by dmfalke** [comment]
Hi @moontrip, I'm unable to build this code, even with linking to @veupathdb/components on the `scatter-control` branch. Is it possible you have local commits you haven't pushed on that branch?

This is the error message I'm getting:
```
/home/dfalke/Work/review/web-eda/src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx
TypeScript error in /home/dfalke/Work/review/web-eda/src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx(423,13):
Type '{ data: any[]; width: number; height: number; xRange: any[]; displayLegend: boolean; displayLibraryControls: boolean; staticPlot: true; margin: { l: number; r: number; b: number; t: number; }; }' is not assignable to type 'IntrinsicAttributes & ScatterplotProps<keyof PlotData>'.
  Property 'displayLegend' does not exist on type 'IntrinsicAttributes & ScatterplotProps<keyof PlotData>'.  TS2322

    421 |             // yRange={[data.value.yMin, data.value.yMax]}
    422 |             // new props for better displaying grid view
  > 423 |             displayLegend={false}
        |             ^
    424 |             displayLibraryControls={false}
    425 |             staticPlot={true}
    426 |             margin={{ l: 40, r: 20, b: 20, t: 10 }}
```

**Comment by moontrip** [comment]
> Hi @moontrip, I'm unable to build this code, even with linking to @veupathdb/components on the `scatter-control` branch. Is it possible you have local commits you haven't pushed on that branch?
> 
> This is the error message I'm getting:
> 
> ```
> /home/dfalke/Work/review/web-eda/src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx
> TypeScript error in /home/dfalke/Work/review/web-eda/src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx(423,13):
> Type '{ data: any[]; width: number; height: number; xRange: any[]; displayLegend: boolean; displayLibraryControls: boolean; staticPlot: true; margin: { l: number; r: number; b: number; t: number; }; }' is not assignable to type 'IntrinsicAttributes & ScatterplotProps<keyof PlotData>'.
>   Property 'displayLegend' does not exist on type 'IntrinsicAttributes & ScatterplotProps<keyof PlotData>'.  TS2322
> 
>     421 |             // yRange={[data.value.yMin, data.value.yMax]}
>     422 |             // new props for better displaying grid view
>   > 423 |             displayLegend={false}
>         |             ^
>     424 |             displayLibraryControls={false}
>     425 |             staticPlot={true}
>     426 |             margin={{ l: 40, r: 20, b: 20, t: 10 }}
> ```

Thank you for your review, @dmfalke . Actually displayLegend prop is defined at ScatterAndLinePlotGeneral component: please see this at web-components's main branch - https://github.com/VEuPathDB/web-components/blob/83129402b679b3af1b24911f3f4cf9f7e39cc196/src/plots/ScatterAndLinePlotGeneral.tsx#L19

I could also see that the latest web-eda has the prop (checked via /node_modules/@veupathdb/components/src/plots/ScatterAndLinePlotGeneral.tsx)

So, my pure guess is that you may not update package at your local, i.e., "yarn install" ?

**Comment by moontrip** [comment]
@dmfalke For clarification, there is nothing left in my local git for web-components repo. 

Another pure guess is that when working with web-component works concerning scatterplot viz (like ScatterAndLinePlotGeneral, ScatterplotControls, useControls, etc.), I did not specifically did 'merge main into <branch>' because of no specific conflicts with others' works. And, I used different branch for ScatterAndLinePlotGeneral (scatter-plot-props branch) and ScatterplotControls (scatter-control branch) made from (possibly) not-updated main branch. Thus, if you are using "yarn link" and scatter-control branch (for using plot control) at your local, then maybe the update at ScatterAndLinePlotGeneral component was not reflected at scatter-control branch. 

Since now scatter-control branch is now merged into main owing to your review and approval, you can update/pull web-component and use main branch for your local "yarn link"

**Comment by dmfalke** [comment]
That's exactly what it is. Since https://github.com/VEuPathDB/web-components/pull/121 is merged, could you merge `main` into this branch so I can test it? As it is, there are compile errors with the latest in https://github.com/VEuPathDB/web-components. Thanks!

**Comment by moontrip** [comment]
I have pushed a commit regarding merge (the latest) main into this branch and resolving merge conflicts. So, this scatter-plot-viz branch is now compatible with the latest web-components' main branch that has the merged ScatterplotControls component now

**Comment by dmfalke** [comment]
Thanks, @moontrip. This is working for me now. I think you can upgrade to the latest version if @veupathdb/components here, obviating the need to use yarn-link.

I think it would be better to put density plot into its own branch. There's really no reason not to. We'll need a PR for it, once the backend is in place, and having a partial implementation in `main` might be confusing.

**Comment by moontrip** [comment]
glad it works for you! And thank you for your info about the bump to the latest version 👍 
Regarding density plot, I also thought of separating it from others, so I will remove density plot from this branch and put it in the other branch like densityplot-viz

**Comment by moontrip** [comment]
@dmfalke two additional commits are made: a) removing density plot from this branch; b) change package.json to the latest web-components version. I could confirm that this worked without relying on yarn link (and the failed check is gone too)

**Review by dmfalke — APPROVED** [review]
Thanks for the changes, @moontrip.

**Pull request merged**
